function [fitresult, gof] = createFit1(frames, time)
%CREATEFIT1(TIMES,AMBULATION)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : frames
%      Y Output: time
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Nov-2011 20:35:25


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( frames, time );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
